package gui;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class AanRegController {
	@FXML
	private Button btnAanmelden;
	@FXML
	private Button btnRegistreren;

	// Event Listener on Button[#btnAanmelden].onAction
	@FXML
	public void btnAanmeldenAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnRegistreren].onAction
	@FXML
	public void btnRegistrerenAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
}
