package gui;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class Hoofdpaneel1Controller {
	@FXML
	private Button btnSpeelSpel;
	@FXML
	private Button btnAfmelden;

	// Event Listener on Button[#btnSpeelSpel].onAction
	@FXML
	public void btnSpeelSpelAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAfmelden].onAction
	@FXML
	public void btnAfmeldenAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
}
