package gui;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class Hoofdpaneel2Controller {
	@FXML
	private ComboBox cmbSpelltjes;
	@FXML
	private Button btnVerlaten;

	// Event Listener on ComboBox[#cmbSpelltjes].onAction
	@FXML
	public void cmbSpelletjesAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnVerlaten].onAction
	@FXML
	public void btnVerlatenAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
}
