package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;
import javafx.scene.layout.GridPane;
import domein.DomeinController;
import javafx.event.ActionEvent;

public class LoginRegistreerSchermController  extends GridPane{
	@FXML
	private Button btnLoginRegistreer;
	private DomeinController dc;
	private HoofdSchermController hs;
	
	
	public LoginRegistreerSchermController(DomeinController dc, HoofdSchermController hs)
	{	
		super();
		this.dc = dc;
		this.hs = hs;
		
		try 
		{
			FXMLLoader loader = new FXMLLoader(getClass().getResource("LoginRegistreerScherm.fxml"));
			loader.setController(this);
			loader.setRoot(this);
			loader.load();
		} catch (Exception ex) 
		{
			System.out.println(ex.getMessage());
		}
	}

	// Event Listener on Button[#btnLoginRegistreer].onAction
	@FXML
	public void btnLoginRegistreerAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
}
