package gui;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class SpelwijzigenController {
	@FXML
	private ComboBox cmbSpellen;
	@FXML
	private ComboBox cmbSpelborden;
	@FXML
	private Button btnWijzig;

	// Event Listener on ComboBox[#cmbSpellen].onAction
	@FXML
	public void cmbSpellenAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#cmbSpelborden].onAction
	@FXML
	public void cmbSpelbordenAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnWijzig].onAction
	@FXML
	public void btnWijzigAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
}
