package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;
import domein.DomeinController;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class SpelMakenSchermController extends GridPane {
	@FXML
	private Button btnMaakSpel;
	@FXML
	private TextField txfSpelMaken;
	@FXML
	private Label lblSpelMaken;

	private DomeinController dc;
	private HoofdSchermController hs;
	
	public SpelMakenSchermController(DomeinController dc, HoofdSchermController hs)
	{
		this.dc = dc;
		this.hs = hs;
		try 
		{
			FXMLLoader loader = new FXMLLoader(getClass().getResource("SpelMakenScherm.fxml"));
			loader.setController(this);
			loader.setRoot(this);
			loader.load();
		} catch (Exception ex) 
		{
			//System.out.println(ex.getMessage());
			ex.printStackTrace();
		}
	}
	
	// Event Listener on Button[#btnMaakSpel].onAction
	@FXML
	public void btnSpelMakenAfhandeling(ActionEvent event) 
	{
		// TODO Autogenerated
	}
}
