package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;
import domein.DomeinController;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.layout.GridPane;

public class SpelwijzigenController extends GridPane
{
	@FXML
	private Label lblSpellen;
	@FXML
	private Label lblSpelborden;
	@FXML
	private ComboBox cmbSpellen;
	@FXML
	private ComboBox cmbSpelborden;
	@FXML
	private Button btnWijzig;
	private DomeinController dc;
	private HoofdSchermController hs;
	@FXML
	private Button btnTerug;
	
	public SpelwijzigenController(DomeinController dc, HoofdSchermController hs)
	{
		this.dc = dc;
		this.hs = hs;
		try 
		{
			FXMLLoader loader = new FXMLLoader(getClass().getResource("Spelwijzigen.fxml"));
			loader.setController(this);
			loader.setRoot(this);
			loader.load();
		} catch (Exception ex) 
		{
			System.out.println(ex.getMessage());
		}
	}

	// Event Listener on ComboBox[#cmbSpellen].onAction
	@FXML
	public void cmbSpellenAfhandeling(ActionEvent event) 
	{
		
	}
	// Event Listener on Button[#btnWijzig].onAction
	@FXML
	public void btnWijzigAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void btnTerugAfhandeling(ActionEvent event) {
		hs.update(new Hoofdpaneel1Controller(dc, hs));
	}
}
