package gui;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class SpelMakenController {
	@FXML
	private Button btnMaakSpel;
	@FXML
	private TextField txtSpelnaam;

	// Event Listener on Button[#btnMaakSpel].onAction
	@FXML
	public void btnMaakSpelAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#txtSpelnaam].onAction
	@FXML
	public void txtSpelnaamAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
}
