package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;
import domein.DomeinController;
import javafx.event.ActionEvent;

public class SpelMakenController extends GridPane
{
	@FXML
	private Button btnMaakSpel;
	@FXML
	private TextField txtSpelnaam;
	private DomeinController dc;
	private HoofdSchermController hs;
	
	public SpelMakenController(DomeinController dc, HoofdSchermController hs)
	{
		this.dc = dc;
		this.hs = hs;
		try 
		{
			FXMLLoader loader = new FXMLLoader(getClass().getResource("SpelMaken.fxml"));
			loader.setController(this);
			loader.setRoot(this);
			loader.load();
		} catch (Exception ex) 
		{
			System.out.println(ex.getMessage());
		}
	}

	// Event Listener on Button[#btnMaakSpel].onAction
	@FXML
	public void btnMaakSpelAfhandeling(ActionEvent event) 
	{
		
	}
	// Event Listener on TextField[#txtSpelnaam].onAction
	@FXML
	public void txtSpelnaamAfhandeling(ActionEvent event) {
		// TODO Autogenerated
	}
}
