package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;

import java.util.Optional;

import domein.DomeinController;
import javafx.application.Platform;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;

public class VoltooiSpelbordSchermController extends GridPane
{
	@FXML
	private GridPane gridSpelbord;
	@FXML
	private Button btnOmlaag;
	@FXML
	private Button btnLinks;
	@FXML
	private Button btnRechts;
	@FXML
	private Button btnOmhoog;
	@FXML
	private Button btnAfsluiten;
	@FXML
	private Label lblAantalVerplaatsingenBoodschap;
	@FXML
	private Label lblAantalVerplaatsingen;
	private DomeinController dc;
	private HoofdSchermController hs;
	
	public VoltooiSpelbordSchermController(DomeinController dc, HoofdSchermController hs)
	{
		this.dc = dc;
		this.hs = hs;
		try 
		{
			FXMLLoader loader = new FXMLLoader(getClass().getResource("VoltooiSpelbordScherm.fxml"));
			loader.setController(this);
			loader.setRoot(this);
			loader.load();
		} catch (Exception ex) 
		{
			System.out.println(ex.getMessage());
		}
		
		btnOmlaag.setText(Taal.getText("omlaag"));
		btnOmhoog.setText(Taal.getText("omhoog"));
		btnLinks.setText(Taal.getText("links"));
		btnRechts.setText(Taal.getText("rechts"));		
		lblAantalVerplaatsingenBoodschap.setText(Taal.getText("verplaatsingen"));
		lblAantalVerplaatsingen.setText("0");
		btnAfsluiten.setText(Taal.getText("closeGui"));
		
		buildGUI();
	}
	
	private void buildGUI()
	{
		
		char[][] veldenStrings = dc.geefVelden();
		
		Image muurImage = new Image(getClass().getResourceAsStream("/images/cobble.jpg"));
		Image leegVeldImage = new Image(getClass().getResourceAsStream("/images/grass.jpg"));
		Image doelImage = new Image(getClass().getResourceAsStream("/images/grassDoel.jpg"));
		Image manImage = new Image(getClass().getResourceAsStream("/images/steve.png"));
		Image kistOkImage = new Image(getClass().getResourceAsStream("/images/chestOk.jpg"));
		Image kistImage = new Image(getClass().getResourceAsStream("/images/chestNietOk.jpg"));
		
		lblAantalVerplaatsingen.setText(String.format("%d",dc.geefAantalVerplaatsingen()));
		
		for (int i = 0; i < 10; i++)
		{
			for (int j = 0; j < 10; j++)
			{
				switch(veldenStrings[i][j])
				{
				case 'M':
					ImageView muur = new ImageView(muurImage);
					muur.setFitHeight(getMaxHeight());
					muur.setFitWidth(getMaxWidth());
					gridSpelbord.add(muur, j, i);
					break;
				case 'X':
					ImageView man = new ImageView(manImage);
					man.setFitHeight(getMaxHeight());
					man.setFitWidth(getMaxWidth());
					gridSpelbord.add(man, j, i);
					break;
				case 'D':
					ImageView doel = new ImageView(doelImage);
					doel.setFitHeight(getMaxHeight());
					doel.setFitWidth(getMaxWidth());
					gridSpelbord.add(doel, j, i);
					break;
				case 'O':
					ImageView leegVeld = new ImageView(leegVeldImage);
					leegVeld.setFitHeight(getMaxHeight());
					leegVeld.setFitWidth(getMaxWidth());
					gridSpelbord.add(leegVeld, j, i);
					break;
				case 'F':
					ImageView kistOk = new ImageView(kistOkImage);
					kistOk.setFitHeight(getMaxHeight());
					kistOk.setFitWidth(getMaxWidth());
					gridSpelbord.add(kistOk, j, i);
					break;
				case 'K':
					ImageView kist = new ImageView(kistImage);
					kist.setFitHeight(getMaxHeight());
					kist.setFitWidth(getMaxWidth());
					gridSpelbord.add(kist, j, i);
					break;
				}
			}
		}
	}

	// Event Listener on Button[#btnOmlaag].onAction
	@FXML
	public void btnOmlaagAfhandeling(ActionEvent event) {
		// TODO Autogenerated
		dc.verplaatsMan("omlaag");
		buildGUI();
	}
	// Event Listener on Button[#btnLinks].onAction
	@FXML
	public void btnLinksAfhandeling(ActionEvent event) {
		// TODO Autogenerated
		dc.verplaatsMan("links");
		buildGUI();
	}
	// Event Listener on Button[#btnRechts].onAction
	@FXML
	public void btnRechtsAfhandeling(ActionEvent event) {
		
		dc.verplaatsMan("rechts");
		buildGUI();
	}
	// Event Listener on Button[#btnOmhoog].onAction
	@FXML
	public void btnOmhoogAfhandeling(ActionEvent event) {
		
		dc.verplaatsMan("omhoog");
		buildGUI();
	}
	// Event Listener on Button[#btnAfsluiten].onAction
	@FXML
	public void btnAfsluitenAfhandeling(ActionEvent event) {
		// TODO Autogenerated
		Alert alert = new Alert(AlertType.CONFIRMATION);
		alert.setTitle(Taal.getText("closeGui"));
		alert.setContentText(Taal.getText("alertAfsluitenGui"));
		
		Optional<ButtonType> result = alert.showAndWait();
		if (result.get() == ButtonType.OK)
		{
			Hoofdpaneel2Controller hp2 = new Hoofdpaneel2Controller(dc, hs);
			Stage stage = (Stage) (getScene().getWindow());
			stage.setScene(hs.getScene());
			
			
//			Scene scene = new Scene(hp2, 400, 300);
//			Stage secondaryStage = (Stage) this.getScene().getWindow();
//			secondaryStage.setScene(scene);
//			secondaryStage.show();
		}
			
		if (result.get() == ButtonType.CANCEL)
			alert.close();
	}
	
	
}
