package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;
import domein.DomeinController;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.GridPane;

public class VoltooiSpelbordSchermController extends GridPane{
	@FXML
	private GridPane gridSpelbord;
	@FXML
	private Button btnOmlaag;
	@FXML
	private Button btnLinks;
	@FXML
	private Button btnRechts;
	@FXML
	private Button btnOmhoog;
	@FXML
	private Button btnAfsluiten;
	@FXML
	private Label lblAantalVerplaatsingenBoodschap;
	@FXML
	private Label lblAantalVerplaatsingen;
	private DomeinController dc;
	private HoofdSchermController hs;
	
	public VoltooiSpelbordSchermController(DomeinController dc, HoofdSchermController hs)
	{
		this.dc = dc;
		this.hs = hs;
		try 
		{
			FXMLLoader loader = new FXMLLoader(getClass().getResource("VoltooiSpelbordScherm.fxml"));
			loader.setController(this);
			loader.setRoot(this);
			loader.load();
		} catch (Exception ex) 
		{
			System.out.println(ex.getMessage());
		}
		
		btnOmlaag.setText(Taal.getText("omlaag"));
		btnOmhoog.setText(Taal.getText("omhoog"));
		btnLinks.setText(Taal.getText("links"));
		btnRechts.setText(Taal.getText("rechts"));		
		lblAantalVerplaatsingenBoodschap.setText(Taal.getText("aantalVerplaatsingen"));
		lblAantalVerplaatsingen.setText("0");
		
		buildGUI();
	}
	
	private void buildGUI()
	{
		char[][] veldenStrings = dc.geefVelden();
		
		ImageView muur = new ImageView(new Image(getClass().getResourceAsStream("/images/cobble.jpg")));
		ImageView leegVeld = new ImageView(new Image(getClass().getResourceAsStream("/images/grass.jpg")));
		ImageView doel = new ImageView(new Image(getClass().getResourceAsStream("/images/grassDoel.jpg")));
		ImageView man = new ImageView(new Image(getClass().getResourceAsStream("/images/steve.png")));
		ImageView kistOk = new ImageView(new Image(getClass().getResourceAsStream("/images/chestOk.jpg")));
		ImageView kist = new ImageView(new Image(getClass().getResourceAsStream("/images/chestNietOk.jpg")));
		
		for (int i = 0; i < 10; i++)
		{
			for (int j = 0; j < 10; j++)
			{
				switch(veldenStrings[i][j])
				{
				case 'X':
					gridSpelbord.add(muur, i, j);
					break;
				case 'M':
					gridSpelbord.add(man, i, j);
					break;
				case 'D':
					gridSpelbord.add(doel, i, j);
					break;
				case '.':
					gridSpelbord.add(leegVeld, i, j);
					break;
				case 'O':
					gridSpelbord.add(kistOk, i, j);
					break;
				case 'K':
					gridSpelbord.add(kist, i, j);
					break;
				}
			}
		}
	}

	// Event Listener on Button[#btnOmlaag].onAction
	@FXML
	public void btnOmlaagAfhandeling(ActionEvent event) {
		// TODO Autogenerated
		dc.verplaatsMan("omlaag");
		buildGUI();
	}
	// Event Listener on Button[#btnLinks].onAction
	@FXML
	public void btnLinksAfhandeling(ActionEvent event) {
		// TODO Autogenerated
		dc.verplaatsMan("links");
		buildGUI();
	}
	// Event Listener on Button[#btnRechts].onAction
	@FXML
	public void btnRechtsAfhandeling(ActionEvent event) {
		
		dc.verplaatsMan("rechts");
		buildGUI();
	}
	// Event Listener on Button[#btnOmhoog].onAction
	@FXML
	public void btnOmhoogAfhandeling(ActionEvent event) {
		
		dc.verplaatsMan("omhoog");
		buildGUI();
	}
	// Event Listener on Button[#btnAfsluiten].onAction
	@FXML
	public void btnAfsluitenAfhandeling(ActionEvent event) {
		// TODO Autogenerated
		hs.update(new Hoofdpaneel1Controller(dc, hs));
	}
	
	
}
